version: '3.8'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: ${NODE_ENV}_nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - api
      - redis
      - postgres
    networks:
      - nestwork
    restart: unless-stopped

  api:
    container_name: "${NODE_ENV}_api"
    image: "${NODE_ENV}_api"
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: ./app
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["./wait-for-postgres.sh", "npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - 9229:9229
    depends_on:
      - redis
      - postgres
    networks:
      - nestwork
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  redis:
    container_name: "${NODE_ENV}_redis"
    image: redis:latest
    networks:
      - nestwork
    restart: unless-stopped
  
  redis-commander:
    container_name: ${NODE_ENV}_commander
    hostname: ${NODE_ENV}_commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
      - redis
    networks:
      - nestwork

  postgres:
    container_name: "${NODE_ENV}_pgsql"
    image: postgres:latest
    networks:
      - nestwork
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    container_name: "${NODE_ENV}_pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    env_file:
      - .env
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    depends_on:
      - postgres
    networks:
      - nestwork
    restart: unless-stopped

networks:
  nestwork: